#!/usr/bin/python

import argparse
from usbtmc import usbtmc

parser = argparse.ArgumentParser()
parser.add_argument('--on', action='store_true',
                    help='Turn on laser diode')
parser.add_argument('--off', action='store_true',
                    help='Turn off laser diode')
parser.add_argument('-p', '--power', metavar='milliwatts',
                    help='Turn off laser diode')
args = parser.parse_args()

dev = usbtmc('/dev/usbtmc0')
dev.write('*IDN?')
idn = dev.read()
if not idn.lower().startswith('thorlabs,itc400'):
    raise RuntimeError('Unsupported device: '+idn)

if args.power is not None:
    dev.write('SOUR:POW %f' % (p / 1000.))

if args.off:
    dev.write('OUTP OFF')
elif args.on:
    dev.write('OUTP:DEL MIN')
    dev.write('OUTP ON')
    dev.write('OUTP:DEL DEF')
else:
    dev.write('OUTP?')
    print dev.read(1)
